BEGIN;
DROP TABLE user_activities;
DROP TABLE user_organisations;
DROP TABLE password_hashes;
DROP TABLE issue_tokens;
DROP TABLE users;
DROP TABLE roles;
DROP TABLE organisations;
DROP TABLE blobs;
DROP TABLE organisations;
DROP TABLE factions;
DROP TABLE roles;
DROP TABLE users;
DROP TABLE user_recovery_codes;
DROP TABLE user_organisations;
DROP TABLE issue_tokens;
DROP TABLE password_hashes;
DROP TABLE user_activities;
DROP TABLE products;
DROP TABLE xsyn_store;
DROP TABLE xsyn_metadata;
DROP TABLE xsyn_assets;
DROP TABLE transactions;
COMMIT;