CREATE DATABASE passport;
CREATE USER passport WITH ENCRYPTED PASSWORD 'dev';
GRANT ALL PRIVILEGES ON DATABASE passport TO passport;
CREATE USER passport_tx WITH ENCRYPTED PASSWORD 'dev-tx';
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
