// Code generated by SQLBoiler 4.8.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DepositAsset1155Transaction is an object representing the database table.
type DepositAsset1155Transaction struct {
	ID             string    `boiler:"id" boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID         string    `boiler:"user_id" boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	CollectionSlug string    `boiler:"collection_slug" boil:"collection_slug" json:"collection_slug" toml:"collection_slug" yaml:"collection_slug"`
	Status         string    `boiler:"status" boil:"status" json:"status" toml:"status" yaml:"status"`
	TXHash         string    `boiler:"tx_hash" boil:"tx_hash" json:"tx_hash" toml:"tx_hash" yaml:"tx_hash"`
	TokenID        int       `boiler:"token_id" boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	Amount         int       `boiler:"amount" boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	CreatedAt      time.Time `boiler:"created_at" boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      null.Time `boiler:"updated_at" boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *depositAsset1155TransactionR `boiler:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L depositAsset1155TransactionL  `boiler:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DepositAsset1155TransactionColumns = struct {
	ID             string
	UserID         string
	CollectionSlug string
	Status         string
	TXHash         string
	TokenID        string
	Amount         string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	UserID:         "user_id",
	CollectionSlug: "collection_slug",
	Status:         "status",
	TXHash:         "tx_hash",
	TokenID:        "token_id",
	Amount:         "amount",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var DepositAsset1155TransactionTableColumns = struct {
	ID             string
	UserID         string
	CollectionSlug string
	Status         string
	TXHash         string
	TokenID        string
	Amount         string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "deposit_asset1155_transactions.id",
	UserID:         "deposit_asset1155_transactions.user_id",
	CollectionSlug: "deposit_asset1155_transactions.collection_slug",
	Status:         "deposit_asset1155_transactions.status",
	TXHash:         "deposit_asset1155_transactions.tx_hash",
	TokenID:        "deposit_asset1155_transactions.token_id",
	Amount:         "deposit_asset1155_transactions.amount",
	CreatedAt:      "deposit_asset1155_transactions.created_at",
	UpdatedAt:      "deposit_asset1155_transactions.updated_at",
}

// Generated where

var DepositAsset1155TransactionWhere = struct {
	ID             whereHelperstring
	UserID         whereHelperstring
	CollectionSlug whereHelperstring
	Status         whereHelperstring
	TXHash         whereHelperstring
	TokenID        whereHelperint
	Amount         whereHelperint
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpernull_Time
}{
	ID:             whereHelperstring{field: "\"deposit_asset1155_transactions\".\"id\""},
	UserID:         whereHelperstring{field: "\"deposit_asset1155_transactions\".\"user_id\""},
	CollectionSlug: whereHelperstring{field: "\"deposit_asset1155_transactions\".\"collection_slug\""},
	Status:         whereHelperstring{field: "\"deposit_asset1155_transactions\".\"status\""},
	TXHash:         whereHelperstring{field: "\"deposit_asset1155_transactions\".\"tx_hash\""},
	TokenID:        whereHelperint{field: "\"deposit_asset1155_transactions\".\"token_id\""},
	Amount:         whereHelperint{field: "\"deposit_asset1155_transactions\".\"amount\""},
	CreatedAt:      whereHelpertime_Time{field: "\"deposit_asset1155_transactions\".\"created_at\""},
	UpdatedAt:      whereHelpernull_Time{field: "\"deposit_asset1155_transactions\".\"updated_at\""},
}

// DepositAsset1155TransactionRels is where relationship names are stored.
var DepositAsset1155TransactionRels = struct {
	User string
}{
	User: "User",
}

// depositAsset1155TransactionR is where relationships are stored.
type depositAsset1155TransactionR struct {
	User *User `boiler:"User" boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*depositAsset1155TransactionR) NewStruct() *depositAsset1155TransactionR {
	return &depositAsset1155TransactionR{}
}

// depositAsset1155TransactionL is where Load methods for each relationship are stored.
type depositAsset1155TransactionL struct{}

var (
	depositAsset1155TransactionAllColumns            = []string{"id", "user_id", "collection_slug", "status", "tx_hash", "token_id", "amount", "created_at", "updated_at"}
	depositAsset1155TransactionColumnsWithoutDefault = []string{"user_id", "collection_slug", "tx_hash", "token_id", "amount", "updated_at"}
	depositAsset1155TransactionColumnsWithDefault    = []string{"id", "status", "created_at"}
	depositAsset1155TransactionPrimaryKeyColumns     = []string{"id"}
)

type (
	// DepositAsset1155TransactionSlice is an alias for a slice of pointers to DepositAsset1155Transaction.
	// This should almost always be used instead of []DepositAsset1155Transaction.
	DepositAsset1155TransactionSlice []*DepositAsset1155Transaction
	// DepositAsset1155TransactionHook is the signature for custom DepositAsset1155Transaction hook methods
	DepositAsset1155TransactionHook func(boil.Executor, *DepositAsset1155Transaction) error

	depositAsset1155TransactionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	depositAsset1155TransactionType                 = reflect.TypeOf(&DepositAsset1155Transaction{})
	depositAsset1155TransactionMapping              = queries.MakeStructMapping(depositAsset1155TransactionType)
	depositAsset1155TransactionPrimaryKeyMapping, _ = queries.BindMapping(depositAsset1155TransactionType, depositAsset1155TransactionMapping, depositAsset1155TransactionPrimaryKeyColumns)
	depositAsset1155TransactionInsertCacheMut       sync.RWMutex
	depositAsset1155TransactionInsertCache          = make(map[string]insertCache)
	depositAsset1155TransactionUpdateCacheMut       sync.RWMutex
	depositAsset1155TransactionUpdateCache          = make(map[string]updateCache)
	depositAsset1155TransactionUpsertCacheMut       sync.RWMutex
	depositAsset1155TransactionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var depositAsset1155TransactionBeforeInsertHooks []DepositAsset1155TransactionHook
var depositAsset1155TransactionBeforeUpdateHooks []DepositAsset1155TransactionHook
var depositAsset1155TransactionBeforeDeleteHooks []DepositAsset1155TransactionHook
var depositAsset1155TransactionBeforeUpsertHooks []DepositAsset1155TransactionHook

var depositAsset1155TransactionAfterInsertHooks []DepositAsset1155TransactionHook
var depositAsset1155TransactionAfterSelectHooks []DepositAsset1155TransactionHook
var depositAsset1155TransactionAfterUpdateHooks []DepositAsset1155TransactionHook
var depositAsset1155TransactionAfterDeleteHooks []DepositAsset1155TransactionHook
var depositAsset1155TransactionAfterUpsertHooks []DepositAsset1155TransactionHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DepositAsset1155Transaction) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DepositAsset1155Transaction) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DepositAsset1155Transaction) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DepositAsset1155Transaction) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DepositAsset1155Transaction) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DepositAsset1155Transaction) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DepositAsset1155Transaction) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DepositAsset1155Transaction) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DepositAsset1155Transaction) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range depositAsset1155TransactionAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDepositAsset1155TransactionHook registers your hook function for all future operations.
func AddDepositAsset1155TransactionHook(hookPoint boil.HookPoint, depositAsset1155TransactionHook DepositAsset1155TransactionHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		depositAsset1155TransactionBeforeInsertHooks = append(depositAsset1155TransactionBeforeInsertHooks, depositAsset1155TransactionHook)
	case boil.BeforeUpdateHook:
		depositAsset1155TransactionBeforeUpdateHooks = append(depositAsset1155TransactionBeforeUpdateHooks, depositAsset1155TransactionHook)
	case boil.BeforeDeleteHook:
		depositAsset1155TransactionBeforeDeleteHooks = append(depositAsset1155TransactionBeforeDeleteHooks, depositAsset1155TransactionHook)
	case boil.BeforeUpsertHook:
		depositAsset1155TransactionBeforeUpsertHooks = append(depositAsset1155TransactionBeforeUpsertHooks, depositAsset1155TransactionHook)
	case boil.AfterInsertHook:
		depositAsset1155TransactionAfterInsertHooks = append(depositAsset1155TransactionAfterInsertHooks, depositAsset1155TransactionHook)
	case boil.AfterSelectHook:
		depositAsset1155TransactionAfterSelectHooks = append(depositAsset1155TransactionAfterSelectHooks, depositAsset1155TransactionHook)
	case boil.AfterUpdateHook:
		depositAsset1155TransactionAfterUpdateHooks = append(depositAsset1155TransactionAfterUpdateHooks, depositAsset1155TransactionHook)
	case boil.AfterDeleteHook:
		depositAsset1155TransactionAfterDeleteHooks = append(depositAsset1155TransactionAfterDeleteHooks, depositAsset1155TransactionHook)
	case boil.AfterUpsertHook:
		depositAsset1155TransactionAfterUpsertHooks = append(depositAsset1155TransactionAfterUpsertHooks, depositAsset1155TransactionHook)
	}
}

// One returns a single depositAsset1155Transaction record from the query.
func (q depositAsset1155TransactionQuery) One(exec boil.Executor) (*DepositAsset1155Transaction, error) {
	o := &DepositAsset1155Transaction{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for deposit_asset1155_transactions")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DepositAsset1155Transaction records from the query.
func (q depositAsset1155TransactionQuery) All(exec boil.Executor) (DepositAsset1155TransactionSlice, error) {
	var o []*DepositAsset1155Transaction

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to DepositAsset1155Transaction slice")
	}

	if len(depositAsset1155TransactionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DepositAsset1155Transaction records in the query.
func (q depositAsset1155TransactionQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count deposit_asset1155_transactions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q depositAsset1155TransactionQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if deposit_asset1155_transactions exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *DepositAsset1155Transaction) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
		qmhelper.WhereIsNull("deleted_at"),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (depositAsset1155TransactionL) LoadUser(e boil.Executor, singular bool, maybeDepositAsset1155Transaction interface{}, mods queries.Applicator) error {
	var slice []*DepositAsset1155Transaction
	var object *DepositAsset1155Transaction

	if singular {
		object = maybeDepositAsset1155Transaction.(*DepositAsset1155Transaction)
	} else {
		slice = *maybeDepositAsset1155Transaction.(*[]*DepositAsset1155Transaction)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &depositAsset1155TransactionR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &depositAsset1155TransactionR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
		qmhelper.WhereIsNull(`users.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(depositAsset1155TransactionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.DepositAsset1155Transactions = append(foreign.R.DepositAsset1155Transactions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.DepositAsset1155Transactions = append(foreign.R.DepositAsset1155Transactions, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the depositAsset1155Transaction to the related item.
// Sets o.R.User to related.
// Adds o to related.R.DepositAsset1155Transactions.
func (o *DepositAsset1155Transaction) SetUser(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"deposit_asset1155_transactions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, depositAsset1155TransactionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &depositAsset1155TransactionR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			DepositAsset1155Transactions: DepositAsset1155TransactionSlice{o},
		}
	} else {
		related.R.DepositAsset1155Transactions = append(related.R.DepositAsset1155Transactions, o)
	}

	return nil
}

// DepositAsset1155Transactions retrieves all the records using an executor.
func DepositAsset1155Transactions(mods ...qm.QueryMod) depositAsset1155TransactionQuery {
	mods = append(mods, qm.From("\"deposit_asset1155_transactions\""))
	return depositAsset1155TransactionQuery{NewQuery(mods...)}
}

// FindDepositAsset1155Transaction retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDepositAsset1155Transaction(exec boil.Executor, iD string, selectCols ...string) (*DepositAsset1155Transaction, error) {
	depositAsset1155TransactionObj := &DepositAsset1155Transaction{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"deposit_asset1155_transactions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, depositAsset1155TransactionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from deposit_asset1155_transactions")
	}

	if err = depositAsset1155TransactionObj.doAfterSelectHooks(exec); err != nil {
		return depositAsset1155TransactionObj, err
	}

	return depositAsset1155TransactionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DepositAsset1155Transaction) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no deposit_asset1155_transactions provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if queries.MustTime(o.UpdatedAt).IsZero() {
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(depositAsset1155TransactionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	depositAsset1155TransactionInsertCacheMut.RLock()
	cache, cached := depositAsset1155TransactionInsertCache[key]
	depositAsset1155TransactionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			depositAsset1155TransactionAllColumns,
			depositAsset1155TransactionColumnsWithDefault,
			depositAsset1155TransactionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(depositAsset1155TransactionType, depositAsset1155TransactionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(depositAsset1155TransactionType, depositAsset1155TransactionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"deposit_asset1155_transactions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"deposit_asset1155_transactions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into deposit_asset1155_transactions")
	}

	if !cached {
		depositAsset1155TransactionInsertCacheMut.Lock()
		depositAsset1155TransactionInsertCache[key] = cache
		depositAsset1155TransactionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the DepositAsset1155Transaction.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DepositAsset1155Transaction) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	queries.SetScanner(&o.UpdatedAt, currTime)

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	depositAsset1155TransactionUpdateCacheMut.RLock()
	cache, cached := depositAsset1155TransactionUpdateCache[key]
	depositAsset1155TransactionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			depositAsset1155TransactionAllColumns,
			depositAsset1155TransactionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update deposit_asset1155_transactions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"deposit_asset1155_transactions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, depositAsset1155TransactionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(depositAsset1155TransactionType, depositAsset1155TransactionMapping, append(wl, depositAsset1155TransactionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update deposit_asset1155_transactions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for deposit_asset1155_transactions")
	}

	if !cached {
		depositAsset1155TransactionUpdateCacheMut.Lock()
		depositAsset1155TransactionUpdateCache[key] = cache
		depositAsset1155TransactionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q depositAsset1155TransactionQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for deposit_asset1155_transactions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for deposit_asset1155_transactions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DepositAsset1155TransactionSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), depositAsset1155TransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"deposit_asset1155_transactions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, depositAsset1155TransactionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in depositAsset1155Transaction slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all depositAsset1155Transaction")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DepositAsset1155Transaction) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no deposit_asset1155_transactions provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	queries.SetScanner(&o.UpdatedAt, currTime)

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(depositAsset1155TransactionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	depositAsset1155TransactionUpsertCacheMut.RLock()
	cache, cached := depositAsset1155TransactionUpsertCache[key]
	depositAsset1155TransactionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			depositAsset1155TransactionAllColumns,
			depositAsset1155TransactionColumnsWithDefault,
			depositAsset1155TransactionColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			depositAsset1155TransactionAllColumns,
			depositAsset1155TransactionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("boiler: unable to upsert deposit_asset1155_transactions, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(depositAsset1155TransactionPrimaryKeyColumns))
			copy(conflict, depositAsset1155TransactionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"deposit_asset1155_transactions\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(depositAsset1155TransactionType, depositAsset1155TransactionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(depositAsset1155TransactionType, depositAsset1155TransactionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert deposit_asset1155_transactions")
	}

	if !cached {
		depositAsset1155TransactionUpsertCacheMut.Lock()
		depositAsset1155TransactionUpsertCache[key] = cache
		depositAsset1155TransactionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single DepositAsset1155Transaction record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DepositAsset1155Transaction) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no DepositAsset1155Transaction provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), depositAsset1155TransactionPrimaryKeyMapping)
	sql := "DELETE FROM \"deposit_asset1155_transactions\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from deposit_asset1155_transactions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for deposit_asset1155_transactions")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q depositAsset1155TransactionQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no depositAsset1155TransactionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from deposit_asset1155_transactions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for deposit_asset1155_transactions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DepositAsset1155TransactionSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(depositAsset1155TransactionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), depositAsset1155TransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"deposit_asset1155_transactions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, depositAsset1155TransactionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from depositAsset1155Transaction slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for deposit_asset1155_transactions")
	}

	if len(depositAsset1155TransactionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DepositAsset1155Transaction) Reload(exec boil.Executor) error {
	ret, err := FindDepositAsset1155Transaction(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DepositAsset1155TransactionSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DepositAsset1155TransactionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), depositAsset1155TransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"deposit_asset1155_transactions\".* FROM \"deposit_asset1155_transactions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, depositAsset1155TransactionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in DepositAsset1155TransactionSlice")
	}

	*o = slice

	return nil
}

// DepositAsset1155TransactionExists checks if the DepositAsset1155Transaction row exists.
func DepositAsset1155TransactionExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"deposit_asset1155_transactions\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if deposit_asset1155_transactions exists")
	}

	return exists, nil
}
