// Code generated by SQLBoiler 4.8.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Faction is an object representing the database table.
type Faction struct {
	ID             string `boiler:"id" boil:"id" json:"id" toml:"id" yaml:"id"`
	VotePrice      string `boiler:"vote_price" boil:"vote_price" json:"votePrice" toml:"votePrice" yaml:"votePrice"`
	ContractReward string `boiler:"contract_reward" boil:"contract_reward" json:"contractReward" toml:"contractReward" yaml:"contractReward"`

	R *factionR `boiler:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L factionL  `boiler:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FactionColumns = struct {
	ID             string
	VotePrice      string
	ContractReward string
}{
	ID:             "id",
	VotePrice:      "vote_price",
	ContractReward: "contract_reward",
}

var FactionTableColumns = struct {
	ID             string
	VotePrice      string
	ContractReward string
}{
	ID:             "factions.id",
	VotePrice:      "factions.vote_price",
	ContractReward: "factions.contract_reward",
}

// Generated where

var FactionWhere = struct {
	ID             whereHelperstring
	VotePrice      whereHelperstring
	ContractReward whereHelperstring
}{
	ID:             whereHelperstring{field: "\"factions\".\"id\""},
	VotePrice:      whereHelperstring{field: "\"factions\".\"vote_price\""},
	ContractReward: whereHelperstring{field: "\"factions\".\"contract_reward\""},
}

// FactionRels is where relationship names are stored.
var FactionRels = struct {
}{}

// factionR is where relationships are stored.
type factionR struct {
}

// NewStruct creates a new relationship struct
func (*factionR) NewStruct() *factionR {
	return &factionR{}
}

// factionL is where Load methods for each relationship are stored.
type factionL struct{}

var (
	factionAllColumns            = []string{"id", "vote_price", "contract_reward"}
	factionColumnsWithoutDefault = []string{}
	factionColumnsWithDefault    = []string{"id", "vote_price", "contract_reward"}
	factionPrimaryKeyColumns     = []string{"id"}
)

type (
	// FactionSlice is an alias for a slice of pointers to Faction.
	// This should almost always be used instead of []Faction.
	FactionSlice []*Faction
	// FactionHook is the signature for custom Faction hook methods
	FactionHook func(boil.Executor, *Faction) error

	factionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	factionType                 = reflect.TypeOf(&Faction{})
	factionMapping              = queries.MakeStructMapping(factionType)
	factionPrimaryKeyMapping, _ = queries.BindMapping(factionType, factionMapping, factionPrimaryKeyColumns)
	factionInsertCacheMut       sync.RWMutex
	factionInsertCache          = make(map[string]insertCache)
	factionUpdateCacheMut       sync.RWMutex
	factionUpdateCache          = make(map[string]updateCache)
	factionUpsertCacheMut       sync.RWMutex
	factionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var factionBeforeInsertHooks []FactionHook
var factionBeforeUpdateHooks []FactionHook
var factionBeforeDeleteHooks []FactionHook
var factionBeforeUpsertHooks []FactionHook

var factionAfterInsertHooks []FactionHook
var factionAfterSelectHooks []FactionHook
var factionAfterUpdateHooks []FactionHook
var factionAfterDeleteHooks []FactionHook
var factionAfterUpsertHooks []FactionHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Faction) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range factionBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Faction) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range factionBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Faction) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range factionBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Faction) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range factionBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Faction) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range factionAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Faction) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range factionAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Faction) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range factionAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Faction) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range factionAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Faction) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range factionAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFactionHook registers your hook function for all future operations.
func AddFactionHook(hookPoint boil.HookPoint, factionHook FactionHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		factionBeforeInsertHooks = append(factionBeforeInsertHooks, factionHook)
	case boil.BeforeUpdateHook:
		factionBeforeUpdateHooks = append(factionBeforeUpdateHooks, factionHook)
	case boil.BeforeDeleteHook:
		factionBeforeDeleteHooks = append(factionBeforeDeleteHooks, factionHook)
	case boil.BeforeUpsertHook:
		factionBeforeUpsertHooks = append(factionBeforeUpsertHooks, factionHook)
	case boil.AfterInsertHook:
		factionAfterInsertHooks = append(factionAfterInsertHooks, factionHook)
	case boil.AfterSelectHook:
		factionAfterSelectHooks = append(factionAfterSelectHooks, factionHook)
	case boil.AfterUpdateHook:
		factionAfterUpdateHooks = append(factionAfterUpdateHooks, factionHook)
	case boil.AfterDeleteHook:
		factionAfterDeleteHooks = append(factionAfterDeleteHooks, factionHook)
	case boil.AfterUpsertHook:
		factionAfterUpsertHooks = append(factionAfterUpsertHooks, factionHook)
	}
}

// One returns a single faction record from the query.
func (q factionQuery) One(exec boil.Executor) (*Faction, error) {
	o := &Faction{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for factions")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Faction records from the query.
func (q factionQuery) All(exec boil.Executor) (FactionSlice, error) {
	var o []*Faction

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to Faction slice")
	}

	if len(factionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Faction records in the query.
func (q factionQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count factions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q factionQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if factions exists")
	}

	return count > 0, nil
}

// Factions retrieves all the records using an executor.
func Factions(mods ...qm.QueryMod) factionQuery {
	mods = append(mods, qm.From("\"factions\""))
	return factionQuery{NewQuery(mods...)}
}

// FindFaction retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFaction(exec boil.Executor, iD string, selectCols ...string) (*Faction, error) {
	factionObj := &Faction{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"factions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, factionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from factions")
	}

	if err = factionObj.doAfterSelectHooks(exec); err != nil {
		return factionObj, err
	}

	return factionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Faction) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no factions provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(factionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	factionInsertCacheMut.RLock()
	cache, cached := factionInsertCache[key]
	factionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			factionAllColumns,
			factionColumnsWithDefault,
			factionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(factionType, factionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(factionType, factionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"factions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"factions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into factions")
	}

	if !cached {
		factionInsertCacheMut.Lock()
		factionInsertCache[key] = cache
		factionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the Faction.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Faction) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	factionUpdateCacheMut.RLock()
	cache, cached := factionUpdateCache[key]
	factionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			factionAllColumns,
			factionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update factions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"factions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, factionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(factionType, factionMapping, append(wl, factionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update factions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for factions")
	}

	if !cached {
		factionUpdateCacheMut.Lock()
		factionUpdateCache[key] = cache
		factionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q factionQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for factions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for factions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FactionSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), factionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"factions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, factionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in faction slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all faction")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Faction) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no factions provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(factionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	factionUpsertCacheMut.RLock()
	cache, cached := factionUpsertCache[key]
	factionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			factionAllColumns,
			factionColumnsWithDefault,
			factionColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			factionAllColumns,
			factionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("boiler: unable to upsert factions, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(factionPrimaryKeyColumns))
			copy(conflict, factionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"factions\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(factionType, factionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(factionType, factionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert factions")
	}

	if !cached {
		factionUpsertCacheMut.Lock()
		factionUpsertCache[key] = cache
		factionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single Faction record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Faction) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no Faction provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), factionPrimaryKeyMapping)
	sql := "DELETE FROM \"factions\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from factions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for factions")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q factionQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no factionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from factions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for factions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FactionSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(factionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), factionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"factions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, factionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from faction slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for factions")
	}

	if len(factionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Faction) Reload(exec boil.Executor) error {
	ret, err := FindFaction(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FactionSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FactionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), factionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"factions\".* FROM \"factions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, factionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in FactionSlice")
	}

	*o = slice

	return nil
}

// FactionExists checks if the Faction row exists.
func FactionExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"factions\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if factions exists")
	}

	return exists, nil
}
