insert into factions (id, label, theme, logo_blob_id, background_blob_id, description)
values  ('98bf7bb3-1a7c-4f21-8843-458d62884060', 'Red Mountain Offworld Mining Corporation', '{"primary": "#C24242", "secondary": "#FFFFFF", "background": "#120E0E"}', '7d5ddbd9-fcd0-414a-9ed3-10c695b0b340', '134ee68e-58a8-4c48-b2bc-f29a7a5a8632', 'Red Mountain is the leader in autonomous mining operations in the Supremacy era. It controls vast territories on Mars, as well as the entire continent formerly known as Australia on Earth. In addition to the production of War Machines, Red Mountain has an economy built on mining, space transportation and energy production. Its AI platforms are directed by REDNET and its leading human assistant is ChiefX. The main tiers of humans include Executives, Engineers and Mechanics.

		By enlisting in Red Mountain, you are joining the greatest interplanetary mining syndicate ever assembled.  '),
        ('7c6dde21-b067-46cf-9e56-155c88a520e2', 'Boston Cybernetics', '{"primary": "#428EC1", "secondary": "#FFFFFF", "background": "#080C12"}', 'c8a8a13d-6f06-478c-8272-d64ca253e6bc', '593a8dbb-00f1-4a51-b893-35030a228247', 'Boston Cybernetics is the major commercial leader within the Supremacy Era. It has expansive territories comprising 275 Districts located along the east coast of the former United States. In addition to the production of War Machines, its economy is built on finance, memory production and the exploration of asteroid belts. Boston Cybernetics AI platforms are directed by BOSSDAN and the human assistant is Patron-A. The three main tiers of humans include Patrons, CyRiders and Stackers. AIs include Synths and Rexeon Guards.

		By enlisting in Boston Cybernetics, you are joining a financial and commercial superpower with plans for space colonization.'),
        ('880db344-e405-428d-84e5-6ebebab1fe6d', 'Zaibatsu Heavy Industries', '{"primary": "#FFFFFF", "secondary": "#000000", "background": "#0D0D0D"}', '040f07e2-28de-4c33-afbe-be6b81be7b43', '043c77d5-ff24-41bc-8faf-2d209144a815', 'Zaibatsu is the industrial leader within the Supremacy era, with heavily populated territories dominated by neon city skyscrapers across the islands formerly known as Japan. In addition to the production of War Machines, Zaibatsu’s economy is built on production optimized by human and AI interaction, as well as the development of future cloud cities. Its AI platforms are directed by ZAIA and the leading human assistant is A1. The three main tiers of humans include APEXRs, KODRs and DENZRs.

		By enlisting in Zaibatsu, you are joining a powerhouse in city construction and industrial production.');
